//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLLopHoc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        public string MASV { get; set; }
        public string TENSV { get; set; }
        public string DIACHI { get; set; }
        public int TUOI { get; set; }
        public string MALOP { get; set; }
    
        public virtual LOPHOC LOPHOC { get; set; }
    }
}
